common: &common
  adapter: mysql2
  host: localhost
  username: root
  password: password
  pool: 8

development: &development
  <<: *common
  database: tatoo_dev

test: &test
  <<: *common
  database: tatoo_test

demo:
  <<: *common
  database: tatoo_demo

production:
  <<: *common
  database: tatoo_production