development:
  bucket: tatoo_dev
  access_key_id: xxx
  secret_access_key: xxx

test:
  bucket: tatoo_test
  access_key_id: xxx
  secret_access_key: xxx

production:
  bucket: tatoo_production
  access_key_id: xxx
  secret_access_key: xxx
